version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - tiktak_elk
  logstash:
    image: logstash:latest
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./volumes/logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5044:5044"
      - "5045:5045"
    networks:
      - tiktak_elk
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:latest
    volumes:
      - ./volumes/kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - tiktak_elk
    depends_on:
      - elasticsearch

networks:
  tiktak_elk:
    driver: bridge
